export interface Case {
  data: {
    type: string;
    attributes: {
      assigned_to_name_c: string;
      name: string;
      contact_c: string;
      resolute_date_c:  string;
      status_case_c: string;
      priority_case_c: string;
      org_name_c:string;
      group_case_c: string;
      modified_user_id: string;
      modified_by_name: string;
      created_by: string;
      created_by_name: string;
      description: string;
      deleted: string;
      created_by_link: string;
      modified_user_link: string;
      assigned_user_id: string;
      assigned_user_name: string;
      assigned_user_link: string;
      SecurityGroups: string;
      case_number: string;
      type: string;
      status: string;
      priority: string;
      resolution: string;
      work_log: string;
      suggestion_box: string;
      account_name: string;
      account_name1: string;
      account_id: string;
      state: string;
      case_attachments_display: string;
      case_update_form: string;
      contact_created_by: string;
      contact_created_by_name: string;
      contact_created_by_id: string;
      tasks: string;
      notes: string;
      meetings: string;
      emails: string;
      documents: string;
      calls: string;
      bugs: string;
      contacts: string;
      accounts: string;
      project: string;
      update_text: string;
      internal: string;
      aop_case_updates_threaded: string;
      aop_case_updates: string;
      aop_case_events: string;
    };
  };
}
