export interface Deal{
    data: {
        type: string;
        attributes: {
            name: string;
            amount_deal_c: string;
            assigned_to_name_c: string;
            close_date_c: string;
            lead_src_c: string;
            org_name_c: string;
            pipe_line_c: string;
            stage_c: string;
            probability_deal_c: string;
            modified_user_id: string;
            modified_by_name: string;
            created_by: string;
            created_by_name: string;
            description: string;
            deleted: string;
            created_by_link: string;
            modified_user_link: string;
            assigned_user_id: string;
            assigned_user_name: string;
            assigned_user_link: string;
            SecurityGroups: string;
            opportunity_type: string;
            account_name: string;
            account_id: string;
            campaign_id: string;
            campaign_name: string;
            campaign_opportunities: string;
            lead_source: string;
            amount: string;
            amount_usdollar: string;
            currency_id: string;
            currency_name: string;
            currency_symbol: string
            date_closed: string;
            next_step: string;
            sales_stage: string;
            probability: string;
            accounts: string;
            contacts: string;
            tasks: string;
            notes: string;
            meetings: string;
            calls: string;
            emails: string;
            documents: string;
            project: string;
            leads: string;
            campaigns: string;
            campaign_link: string;
            currencies: string;
            aos_quotes: string;
            aos_contracts: string;
        }
    }
}